language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
 # - npm install
 # - npm run test
  - npm run build
deploy:
  provider: pages
  cleanup: false
  github_token: $github_token
  local_dir: build
  on:
    branch: master